-- MySQL Script generated by MySQL Workbench
-- Wed Aug 26 21:14:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema diagrama
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `diagrama` ;

-- -----------------------------------------------------
-- Schema diagrama
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `diagrama` DEFAULT CHARACTER SET utf8 ;
USE `diagrama` ;

-- -----------------------------------------------------
-- Table `diagrama`.`UniaoFederativa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diagrama`.`UniaoFederativa` ;

CREATE TABLE IF NOT EXISTS `diagrama`.`UniaoFederativa` (
  `idUniaoFederativa` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUniaoFederativa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diagrama`.`Cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diagrama`.`Cidade` ;

CREATE TABLE IF NOT EXISTS `diagrama`.`Cidade` (
  `idCidade` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `idUniaoFederativa` INT NOT NULL,
  PRIMARY KEY (`idCidade`),
  INDEX `fk_Cidade_UniaoFederativa1_idx` (`idUniaoFederativa` ASC) VISIBLE,
  CONSTRAINT `fk_Cidade_UniaoFederativa1`
    FOREIGN KEY (`idUniaoFederativa`)
    REFERENCES `diagrama`.`UniaoFederativa` (`idUniaoFederativa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diagrama`.`Bairro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diagrama`.`Bairro` ;

CREATE TABLE IF NOT EXISTS `diagrama`.`Bairro` (
  `idBairro` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBairro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diagrama`.`Rua`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diagrama`.`Rua` ;

CREATE TABLE IF NOT EXISTS `diagrama`.`Rua` (
  `idRua` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRua`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diagrama`.`Endereço`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diagrama`.`Endereço` ;

CREATE TABLE IF NOT EXISTS `diagrama`.`Endereço` (
  `idEndereço` INT NOT NULL,
  `Cidade_idCidade` INT NOT NULL,
  `idBairro` INT NOT NULL,
  `idRua` INT NOT NULL,
  `CEP` VARCHAR(10) NOT NULL,
  `Numero` VARCHAR(45) NOT NULL,
  `Complemento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEndereço`),
  INDEX `fk_Endereço_Cidade1_idx` (`Cidade_idCidade` ASC) VISIBLE,
  INDEX `fk_Endereço_Bairro1_idx` (`idBairro` ASC) VISIBLE,
  INDEX `fk_Endereço_Rua1_idx` (`idRua` ASC) VISIBLE,
  CONSTRAINT `fk_Endereço_Cidade1`
    FOREIGN KEY (`Cidade_idCidade`)
    REFERENCES `diagrama`.`Cidade` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereço_Bairro1`
    FOREIGN KEY (`idBairro`)
    REFERENCES `diagrama`.`Bairro` (`idBairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereço_Rua1`
    FOREIGN KEY (`idRua`)
    REFERENCES `diagrama`.`Rua` (`idRua`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diagrama`.`Agenda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diagrama`.`Agenda` ;

CREATE TABLE IF NOT EXISTS `diagrama`.`Agenda` (
  `idAgenda` INT NOT NULL,
  `Data` DATE NOT NULL,
  `Mensagem` VARCHAR(45) NOT NULL,
  `EnderecoId` INT NOT NULL,
  `Histórico` VARCHAR(45) NOT NULL,
  `Hora` TIME NOT NULL,
  PRIMARY KEY (`idAgenda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diagrama`.`Usuário`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diagrama`.`Usuário` ;

CREATE TABLE IF NOT EXISTS `diagrama`.`Usuário` (
  `idTable` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(14) NOT NULL,
  `senha` VARCHAR(10) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `EnderecoId` INT NOT NULL,
  `Prestador` VARCHAR(45) NULL,
  `idEndereço` INT NOT NULL,
  `Agenda_idAgenda` INT NOT NULL,
  `Categoria_Serviço` VARCHAR(45) NULL,
  PRIMARY KEY (`idTable`),
  INDEX `fk_Usuário_Endereço1_idx` (`idEndereço` ASC) VISIBLE,
  INDEX `fk_Usuário_Agenda1_idx` (`Agenda_idAgenda` ASC) VISIBLE,
  CONSTRAINT `fk_Usuário_Endereço1`
    FOREIGN KEY (`idEndereço`)
    REFERENCES `diagrama`.`Endereço` (`idEndereço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuário_Agenda1`
    FOREIGN KEY (`Agenda_idAgenda`)
    REFERENCES `diagrama`.`Agenda` (`idAgenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diagrama`.`Publicação`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diagrama`.`Publicação` ;

CREATE TABLE IF NOT EXISTS `diagrama`.`Publicação` (
  `idPublicação` INT NOT NULL,
  `Descrição` VARCHAR(45) NOT NULL,
  `Foto` VARCHAR(45) NOT NULL,
  `Usuário_idTable` INT NOT NULL,
  `Categoria_Serviço` VARCHAR(45) NULL,
  PRIMARY KEY (`idPublicação`),
  INDEX `fk_Publicação_Usuário1_idx` (`Usuário_idTable` ASC) VISIBLE,
  CONSTRAINT `fk_Publicação_Usuário1`
    FOREIGN KEY (`Usuário_idTable`)
    REFERENCES `diagrama`.`Usuário` (`idTable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diagrama`.`Chat de Conversa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diagrama`.`Chat de Conversa` ;

CREATE TABLE IF NOT EXISTS `diagrama`.`Chat de Conversa` (
  `idAba de Conversa` INT NOT NULL,
  `UsuarioEmitenteId` INT NOT NULL,
  `Mensagem` VARCHAR(280) NULL,
  `UsuarioRemetenteId` INT NOT NULL,
  PRIMARY KEY (`idAba de Conversa`),
  INDEX `idTable _idx` (`UsuarioEmitenteId` ASC) VISIBLE,
  CONSTRAINT `idTable `
    FOREIGN KEY (`UsuarioEmitenteId`)
    REFERENCES `diagrama`.`Usuário` (`idTable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
