-- MySQL Script generated by MySQL Workbench
-- Tue Sep  8 20:09:39 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema grittoDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema grittoDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `grittoDB` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema dadospessoais
-- -----------------------------------------------------
USE `grittoDB` ;

-- -----------------------------------------------------
-- Table `grittoDB`.`UniaoFederativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grittoDB`.`UniaoFederativa` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grittoDB`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grittoDB`.`Cidade` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `uf_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cidade_UniaoFederativa1_idx` (`uf_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `uf_id_UNIQUE` (`uf_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cidade_UniaoFederativa1`
    FOREIGN KEY (`uf_id`)
    REFERENCES `grittoDB`.`UniaoFederativa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grittoDB`.`Bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grittoDB`.`Bairro` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grittoDB`.`Rua`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grittoDB`.`Rua` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grittoDB`.`Endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grittoDB`.`Endereço` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cidade_id` BIGINT UNSIGNED NOT NULL,
  `bairro_id` BIGINT UNSIGNED NOT NULL,
  `rua_id` BIGINT UNSIGNED NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Endereço_Cidade1_idx` (`cidade_id` ASC) VISIBLE,
  INDEX `fk_Endereço_Bairro1_idx` (`bairro_id` ASC) VISIBLE,
  INDEX `fk_Endereço_Rua1_idx` (`rua_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `cidade_id_UNIQUE` (`cidade_id` ASC) VISIBLE,
  UNIQUE INDEX `bairro_id_UNIQUE` (`bairro_id` ASC) VISIBLE,
  UNIQUE INDEX `idRua_UNIQUE` (`rua_id` ASC) VISIBLE,
  CONSTRAINT `fk_Endereço_Cidade1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `grittoDB`.`Cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereço_Bairro1`
    FOREIGN KEY (`bairro_id`)
    REFERENCES `grittoDB`.`Bairro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereço_Rua1`
    FOREIGN KEY (`rua_id`)
    REFERENCES `grittoDB`.`Rua` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grittoDB`.`Agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grittoDB`.`Agenda` (
  `id` BIGINT UNSIGNED NOT NULL,
  `data` DATE NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `historico` VARCHAR(45) NOT NULL,
  `hora` TIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grittoDB`.`Categoria_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grittoDB`.`Categoria_servico` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_servico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grittoDB`.`Usuário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grittoDB`.`Usuário` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `senha` VARCHAR(10) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `prestador` TINYINT NULL,
  `endereco_id` INT NOT NULL,
  `agenda_id` INT NOT NULL,
  `numero` INT NOT NULL,
  `complemento` VARCHAR(45) NOT NULL,
  `cat_servico_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Usuário_Endereço1_idx` (`endereco_id` ASC) VISIBLE,
  INDEX `fk_Usuário_Agenda1_idx` (`agenda_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Usuário_Categoria_servico1_idx` (`cat_servico_id` ASC) VISIBLE,
  CONSTRAINT `fk_Usuário_Endereço1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `grittoDB`.`Endereço` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuário_Agenda1`
    FOREIGN KEY (`agenda_id`)
    REFERENCES `grittoDB`.`Agenda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuário_Categoria_servico1`
    FOREIGN KEY (`cat_servico_id`)
    REFERENCES `grittoDB`.`Categoria_servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grittoDB`.`Publicação`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grittoDB`.`Publicação` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricacao` VARCHAR(280) NOT NULL,
  `foto` VARCHAR(60) NULL,
  `usuario_id` INT NOT NULL,
  `endereco_id` BIGINT UNSIGNED NOT NULL,
  `cat_servico_id` BIGINT UNSIGNED NOT NULL,
  `numero` INT NULL,
  `complemento` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Publicação_Usuário1_idx` (`usuario_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Publicação_Endereço1_idx` (`endereco_id` ASC) VISIBLE,
  INDEX `fk_Publicação_Categoria_servico1_idx` (`cat_servico_id` ASC) VISIBLE,
  CONSTRAINT `fk_Publicação_Usuário1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `grittoDB`.`Usuário` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Publicação_Endereço1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `grittoDB`.`Endereço` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Publicação_Categoria_servico1`
    FOREIGN KEY (`cat_servico_id`)
    REFERENCES `grittoDB`.`Categoria_servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grittoDB`.`Chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grittoDB`.`Chat` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Mensagem` VARCHAR(280) NULL,
  `usuario_remetente_id` BIGINT UNSIGNED NOT NULL,
  `usuario_destinatario_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Chat_Usuário1_idx` (`usuario_remetente_id` ASC) VISIBLE,
  INDEX `fk_Chat_Usuário2_idx` (`usuario_destinatario_id` ASC) VISIBLE,
  CONSTRAINT `fk_Chat_Usuário1`
    FOREIGN KEY (`usuario_remetente_id`)
    REFERENCES `grittoDB`.`Usuário` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Chat_Usuário2`
    FOREIGN KEY (`usuario_destinatario_id`)
    REFERENCES `grittoDB`.`Usuário` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
